apiVersion: v1
kind: Service
metadata:
  name: {{ "{{ include \"app.fullname\" . }}" }}-backend
  namespace: {{ "{{ .Values.global.namespace }}" }}
spec:
  selector:
    app.kubernetes.io/name: {{ "{{ include \"app.fullname\" . }}" }}-backend
  ports:
    - port: {{ "{{ .Values.backend.port }}" }}
      targetPort: {{ "{{ .Values.backend.port }}" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ "{{ include \"app.fullname\" . }}" }}-frontend
  namespace: {{ "{{ .Values.global.namespace }}" }}
spec:
  selector:
    app.kubernetes.io/name: {{ "{{ include \"app.fullname\" . }}" }}-frontend
  ports:
    - port: {{ "{{ .Values.frontend.port }}" }}
      targetPort: {{ "{{ .Values.frontend.port }}" }}
